### ISSUE TITLE
Failed to parse incoming request: runtime error: index out of range [0] with length 0

### ISSUE THREAD

**Issue by crouthamela** [tedpearson/ambientweatherexporter#1]
Hi there, I have a WS-2902A and have it working according to the instructions. On my server I'm receiving the error message "Failed to parse incoming request: runtime error: index out of range [0] with length 0".

My /metrics currently look like:
battery{name="Yorkshire Estates",sensor="outdoor"} 0
temperature{name="Yorkshire Estates",sensor="dewpoint"} 35.80457327367417
temperature{name="Yorkshire Estates",sensor="feelsLike"} 45
temperature{name="Yorkshire Estates",sensor="indoor"} 72
temperature{name="Yorkshire Estates",sensor="outdoor"} 45

It stops there. Could you help me diagnose the bad data causing the metrics to stop part way through?

**Comment by tedpearson** [comment]
Hi @crouthamela! Could you obtain the data your weather station is sending to the server? Here's how I would do that: 
1. Install netcat via `sudo apt install netcat-openbsd` (assuming you are running on debian-based linux)
2. Stop ambientweatherexporter
3. Run netcat listening on the port ambientweatherexporter was listening on: `nc -l 1234`
4. If you still have a prometheus or other metrics scraper running, you may see its requests, ctrl-c to close the connection, restart `nc` to listen again
5. You should end up with output something like this: 
```ted@raspberrypi:~ $ nc -l 2184
GET /data/report/stationtype=AMBWeatherV4.3.2&PASSKEY=XX:XX:XX:XX:XX:XX&dateutc=2024-02-10+03:34:26&tempinf=65.8&battin=1&humidityin=61&baromrelin=29.959&baromabsin=29.519&tempf=49.8&battout=1&humidity=68&winddir=87&winddir_avg10m=87&windspeedmph=0.2&windspdmph_avg10m=0.7&windgustmph=1.1&maxdailygust=8.1&hourlyrainin=0.000&eventrainin=0.000&dailyrainin=0.000&weeklyrainin=0.000&monthlyrainin=0.000&yearlyrainin=6.480&solarradiation=0.00&uv=0&temp2f=68.2&humidity2=51&temp3f=67.1&humidity3=54&temp4f=59.7&humidity4=57&temp5f=70.2&humidity5=55&batt2=1&batt3=1&batt4=1&batt5=1&batt_co2=1 HTTP/1.1
Host: 192.168.1.198
Connection: close
User-Agent: ESP8266
```

I should be able to debug the issue with that output. 😃

**Comment by crouthamela** [comment]
Thanks! Here is the output:

GET /data/report/stationtype=AMBWeatherV4.3.4&PASSKEY=80:7D:3A:49:6E:AB&dateutc=2024-02-10+03:44:32&tempinf=71.4&humidityin=33&baromrelin=29.761&baromabsin=29.610&tempf=44.8&humidity=71&winddir=76&windspeedmph=0.7&windgustmph=1.1&maxdailygust=9.2&hourlyrainin=0.000&eventrainin=0.000&dailyrainin=0.000&weeklyrainin=0.000&monthlyrainin=0.189&totalrainin=236.220&solarradiation=0.00&uv=0&batt_co2=1 HTTP/1.1
Host: 192.168.77.251
Connection: close
User-Agent: ESP8266

**Comment by tedpearson** [comment]
Found the issue! The code was expecting "battout", "battin", and "yearlyrainin" as parameters in the url. I've fixed that issue and made it more robust to any missing previously expected params in the url. I just released [v1.5.0](https://github.com/tedpearson/ambientweatherexporter/releases/tag/v1.5.0), please check it out and let me know if it works!

**Comment by crouthamela** [comment]
That fixed it for me, thanks! I checked the data in /metrics vs the netcat output and I'm missing a few datapoints. Would you be willing to implement these few?

tempf=44.8             (outdoor temp)
humidity=71            (outdoor humidity)
windgustmph=1.1
maxdailygust=9.2
hourlyrainin=0.000

PS - Haven't seen Trogdor in a long time!

**Comment by tedpearson** [comment]
Oops, I inverted some error checks. You should get these fields as well from [v1.5.1:](https://github.com/tedpearson/ambientweatherexporter/releases/tag/v1.5.1)
- temperature{sensor="outdoor"}
- wind_speed_mph{type="sustained"}
- humidity{sensor="outdoor"}
- dewpoint
- temperature{sensor="dewpoint"}
- temperature{sensor="feelsLike"}

**Comment by crouthamela** [comment]
Looking good now, thanks!

**Comment by tedpearson** [comment]
Awesome! Hope it meets your needs.

And the Trogdor comes in the night!
